### ISSUE TITLE
v4.4 Feature plan (aka todo)

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli#298]
- [x] Caching API #314 
- [x] Scraper typo hinting
- [x] fzf image preview support #321
- [x] ~~`-r` / `--range` #226~~ (moved to a later update)
- [x] Refactor players and remove `PlayerNotSupported()`.
- [x] Remove `MediaNotFound()`.
- [x] scraper configs #291
- [x] yt dlp downloading #299 
- [x] metadata overridable display name
- [x] .env file for credentials
- [x] fix going back a season resets the episode to episode 1 #292
- [x] `--limit` WHY DOES THIS STILL NOT EXIST??
- [x] better implementation of quality config key #308 
- [x] http request timeout adjustable in the config https://github.com/mov-cli/mov-cli/commit/99461df36c8174a745569de22eb065c40d073fec
- [x] try and hide ips in debug mode https://github.com/mov-cli/mov-cli/pull/313
- [x] allow user to disable watch options
- [x] add limit to config too
- [x] method in `Media()` to retrive stream quality.
- [x] include stream quality in "Playing 'x'..." text.
- [x] custom player args support. https://github.com/mov-cli/mov-cli/issues/323
- [x] non temp cache system
- [x] cache the update checker

*List is wip...*

**Comment by THEGOLDENPRO** [comment]
### Documentation
Features that need to be documented in the wiki.
- [x] Scraper configs
- [x] subtitles
- [x] watch_options
- [x] hide ip
- [x] limit
- [x] display_quality
- [x] install via aur
- [x] debug player in debug key
- [x] http timeout
- [x] yt dlp downloading
- [x] environment variables config (use this for confidential stuff)
- [x] fzf image preview
- [x] binary and args key in `[mov-cli.player]`.
